services:
  - type: pserv
    name: backend
    env: java
    branch: master
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    rootDir: backend
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/valhallawebsite-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080

  - type: web
    name: frontend
    env: static
    branch: master
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist/front_valhalla
