services:
  - type: web
    name: backend
    env: java
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    branch: main
    buildCommand: ./gradlew build
    startCommand: java -jar backend/build/libs/valhallawebsite-0.0.1-SNAPSHOT.jar
    rootDir: backend

  - type: web
    name: frontend
    env: static
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist/front_valhalla