services:
  - type: web
    name: backend
    env: java17
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    branch: master
    buildCommand: chmod +x ./gradlew && ./gradlew build
    startCommand: java -jar backend/build/libs/valhallawebsite-0.0.1-SNAPSHOT.jar
    rootDir: backend
    envVars:
      - key: JAVA_VERSION
        value: 17

  - type: web
    name: frontend
    env: static
    repo: https://github.com/FyarX/TFC_ValhallaFitnessTemple
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist/front_valhalla